services:
  django:
    restart: always
    image: admintotal/desktop:latest
    container_name: desktop-django
    command: >
      bash -c "./docker/wait-for-it.sh db:5433 -- ./docker/wait-for-it.sh redis:6379 -- python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:7000 --timeout 60 --max-requests 500 --max-requests-jitter 50"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    
  nginx:
    restart: always
    image: admintotal/desktop-nginx:latest
    container_name: desktop-nginx
    command: >
      bash -c "/usr/src/app/wait-for-it.sh django:7000 -- nginx -g 'daemon off;'"
    ports:
      - "3001:3000"
      - "8081:80"
    depends_on:
      - django

  celery:
    restart: always
    image: admintotal/desktop:latest
    container_name: desktop-celery
    command: >
      bash -c "/usr/src/app/docker/wait-for-it.sh django:7000 -- celery -A core worker -E -l INFO --max-tasks-per-child=50"
    env_file:
      - .env
    depends_on:
      - django
      - redis

  celery_beat:
    restart: always
    image: admintotal/desktop:latest
    container_name: desktop-celery_beat
    command: >
      bash -c "/usr/src/app/docker/wait-for-it.sh django:7000 -- celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    env_file:
      - .env
    depends_on:
      - django
      - redis

  db:
    restart: always
    image: postgres:17
    container_name: desktop-db
    command: -p 5433
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  redis:
    restart: always
    image: redis:7.4.1
    container_name: desktop-redis

volumes:
  postgres_data:
